apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus.prometheus.svc.cluster.local:9090
    isDefault: true
    editable: true
    jsonData:
      timeInterval: 30s
      keepCookies: []
    secureJsonData: {}
  
  - name: Alertmanager
    type: alertmanager
    access: proxy
    url: http://alertmanager.prometheus.svc.cluster.local:9093
    isDefault: false
    editable: true
    jsonData:
      implementation: prometheus
